### ISSUE TITLE
Offerings: Adding Options UX (can form addition be un-collapsed?)

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#505] opened 2023-07-14 22:12 UTC
Minor UX issue

When I add an option to an Offering, at first I didn't see that the added option was there, because it was collapsed, and appeared above the "Add Option" button. When adding an option to an Offering, could that part of the form appear immediately editable/ "un-collapsed"?

<img width="866" alt="Screen Shot 2023-07-14 at 5 07 33 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/b3a25253-9e67-498c-b1cc-c9681c301802">

**Comment by zkat** [comment] 2023-07-18 00:18
moving post-MVP

**Comment by zkat** [comment] 2023-08-19 22:04
Closing as duplicate of https://github.com/BanchanArt/banchan/issues/609

**Closed** 2023-08-19 22:04 UTC
Labels: enhancement, bug bash, ux
