### ISSUE TITLE
Pixel art is enlarged and blurry, not pretty.

### ISSUE THREAD

**Issue by banchan-tokki** [BanchanArt/banchan#502] opened 2023-07-14 01:23 UTC
reported by [@camyza_0](https://dev.banchan.art/denizens/camyza_0):

As discussed in vc, art is enlarged and blurry. Making it highly unviewable. Even the gallery images which aren't even that small when uploaded.

**Comment by zkat** [comment] 2023-07-15 21:23
Duplicate of #497

**Closed by zkat** 2023-07-15 21:23 UTC
Labels: bug, from-site, bug bash
