### ISSUE TITLE
Markdown editor script warnings

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#506] opened 2023-07-14 22:29 UTC
In the Markdown editor, sometimes inserting a break (pressing Return) in the WYSIWYG editor results in a script warning. But that has NoT happened _every_ time "enter" was pressed in this field.

NOTE: It's not just when it is within a Table, I had this happening in the plain text part as well.

![disallowed](https://github.com/BanchanArt/banchan/assets/5471856/239c7680-9667-4d47-80bd-9bba45e95496)
<img width="966" alt="Screen Shot 2023-07-14 at 5 27 03 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/4c1f5cc5-8a6c-47d0-b90c-bac44d2bf537">

**Comment by zkat** [comment] 2023-07-15 00:20
Duplicate of #455

**Closed by zkat** 2023-07-15 00:20 UTC
